;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
	backward-kill-dwim
	crux-move-beginning-of-line
	helm-M-x
	ignore
	mouse-set-region
	toggle-korean-input-method
	xref-find-apropos
	))

(setq mc/cmds-to-run-once
      '(
	))
